var json =
{"Stds Alignments":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"stds",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"focus-area",
"nodeFrom":"stds",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"initiative",
"nodeFrom":"stds",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"intervention",
"nodeFrom":"stds",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"arch",
"nodeFrom":"stds",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#800000",
"$type":"rectangle",
"description":""},
"id":"stds",
"name":"STANDARDS ALIGNMENTS"},

"CSF":{"adjacencies":[],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf",
"name":"CRITICAL SUCCESS FACTORS (CSF)"},

"Focus Areas":{"adjacencies":[],
"data":{"$color":"#F6358A",
"$type":"triangle",
"description":""},
"id":"focus-area",
"name":"FOCUS AREAS (FA)"},

"Initiatives":{"adjacencies":[],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"initiative",
"name":"STANDARDS INITIATIVES"},

"Interventions":{"adjacencies":[],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"intervention",
"name":"INTERVENTIONS (IV)"},

"Arch View":{"adjacencies":[],
"data":{"$color":"#636453",
"$type":"ellipse",
"description":""},
"id":"arch",
"name":"ARCH VIEW"},

"1: Formal Language":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf01",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf01",
"name":"CSF01: Formal Language"},

"2: Computability":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf02",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf02",
"name":"CSF02: Computability"},

"3: Ingest Care Pathways":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf03",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf03",
"name":"CSF03: Ingest Care Pathways"},

"4: Data Semantics":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf04",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf04",
"name":"CSF04: Data Semantics"},

"5: Standard APIs":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf05",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf05",
"name":"CSF05: Standard APIs"},

"6: Standards-Based Care Plan":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf06",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf06",
"name":"CSF06: Standards-Based Care Plan"},

"7: Distributed Trust":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf07",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf07",
"name":"CSF07: Distributed Trust"},

"8: Publish/Subscribe":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf08",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf08",
"name":"CSF08: Publish/Subscribe"},

"9: Integrative Data Remediation":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf09",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf09",
"name":"CSF09: Integrative Data Remediation"},

"10: Multi-Org Care Mgmt":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf10",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf10",
"name":"CSF010: Multi-Org Care Mgmt"},

"11: Knowledge Ecosystem":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf11",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf11",
"name":"CSF11: Knowledge Ecosystem"},

"12: Integrated CDS":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf12",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf12",
"name":"CSF12: Integrated CDS"},

"13: Stds-based Longitudinal Record":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf13",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf13",
"name":"CSF13: Stds-based Longitudinal Record"},

"14: Exchange":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf14",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf14",
"name":"CSF14: Exchange"},

"15: Discovery":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf15",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf15",
"name":"CSF15: Discovery"},

"16: Feedback":{"adjacencies":[
{"nodeTo":"csf",
"nodeFrom":"csf16",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#2121FF",
"$type":"square",
"description":""},
"id":"csf16",
"name":"CSF16: Feedback"},

"1: Content Authoring":{"adjacencies":[
{"nodeTo":"focus-area",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf01",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#F6358A",
"$type":"triangle",
"description":""},
"id":"authoring",
"name":"FA1: Content Authoring"},

"2: Content Consumption":{"adjacencies":[
{"nodeTo":"focus-area",
"nodeFrom":"consumption",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf15",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#F6358A",
"$type":"triangle",
"description":""},
"id":"consumption",
"name":"FA2: Content Consumption"},

"3: Information Sharing":{"adjacencies":[
{"nodeTo":"focus-area",
"nodeFrom":"information-sharing",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf14",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#F6358A",
"$type":"triangle",
"description":""},
"id":"information-sharing",
"name":"FA3: Information Sharing"},

"4: CDS":{"adjacencies":[
{"nodeTo":"focus-area",
"nodeFrom":"cds",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#F6358A",
"$type":"triangle",
"description":""},
"id":"cds",
"name":"FA4: CDS"},

"5: Care Coordination":{"adjacencies":[
{"nodeTo":"focus-area",
"nodeFrom":"care-coordination",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf06",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf10",
"nodeFrom":"authoring",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#F6358A",
"$type":"triangle",
"description":""},
"id":"care-coordination",
"name":"FA5: Care Coordination"},

"Adapting Guidelines":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"adapting-guidelines",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"adapting-guidelines",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"adapting-guidelines",
"name":"Adapting Guidelines for Digital Age"},

"API4KP":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"api4kp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"api4kp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"api4kp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"api4kp",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"api4kp",
"name":"API4KP"},

"Arden":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"arden",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf01",
"nodeFrom":"arden",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"arden",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"arden",
"name":"Arden"},

"BPM+":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"bpm+",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf01",
"nodeFrom":"bpm+",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"bpm+",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"bpm+",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf10",
"nodeFrom":"bpm+",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"bpm+",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"bpm+",
"name":"BPM+"},

"CCS":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"ccs",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"ccs",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"ccs",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf10",
"nodeFrom":"ccs",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"business",
"nodeFrom":"ccs",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"ccs",
"name":"CCS"},

"CDA/C-CDA":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cda",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"cda",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"cda",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"cda",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"cda",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cda",
"name":"CDA/C-CDA"},

"CDS Connect":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cds-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"cds-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"cds-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"business",
"nodeFrom":"cds-c",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cds-c",
"name":"CDS Connect"},

"CDS Connect Authoring":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cds-c-authoring",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"cds-c-authoring",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cds-c-authoring",
"name":"CDS Connect Authoring"},

"CDS Connect Repository":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cds-c-repository",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"cds-c-repository",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cds-c-repository",
"name":"CDS Connect Repository"},

"CDS Hooks":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cds-hooks",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"cds-hooks",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf15",
"nodeFrom":"cds-hooks",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"cds-hooks",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cds-hooks",
"name":"CDS Hooks"},

"CIMI":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cimi",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"cimi",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"cimi",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"cimi",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cimi",
"name":"CIMI"},

"Clinical Guidelines in CIIC":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"c-g-ciic",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"c-g-ciic",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"business",
"nodeFrom":"c-g-ciic",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"c-g-ciic",
"name":"Clinical Guidelines in CIIC"},

"Clinical Guidelines on FHIR":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"c-g-fhir",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"c-g-fhir",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"c-g-fhir",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"business",
"nodeFrom":"c-g-fhir",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"c-g-fhir",
"name":"Clinical Guidelines on FHIR"},

"Clinical Terminologies":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"c-term",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"c-term",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"c-term",
"name":"Clinical Terminologies"},

"CDMH on FHIR":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cdmh-fhir",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"cdmh-fhir",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"cdmh-fhir",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cdmh-fhir",
"name":"CDMH on FHIR"},

"Composite Knowledge Artifacts":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"c-k-artifacts",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"c-k-artifacts",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"c-k-artifacts",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"c-k-artifacts",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"c-k-artifacts",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"c-k-artifacts",
"name":"Composite Knowledge Artifacts"},

"CQL/FHIRPath":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cql",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf01",
"nodeFrom":"cql",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"cql",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"cql",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"cql",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"cql",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cql",
"name":"CQL/FHIRPath"},

"CDS/DSS":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"cds-dss",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"cds-dss",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"business",
"nodeFrom":"cds-dss",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"cds-dss",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"cds-dss",
"name":"CDS/DSS"},

"DICOM":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"dicom",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"dicom",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"dicom",
"name":"DICOM"},

"DaVinci DTR":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"davinchi",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"davinchi",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"davinchi",
"name":"DaVinci DTR"},

"Drug-Drug Interaction CDS":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"drug-drug",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"business",
"nodeFrom":"drug-drug",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"drug-drug",
"name":"Drug-Drug Interaction CDS"},

"eCQM":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"ecqm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"ecqm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"ecqm",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"ecqm",
"name":"eCQM"},

"ELM":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"elm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf01",
"nodeFrom":"elm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"elm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"elm",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"elm",
"name":"ELM"},

"EBM on FHIR":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"ebm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"ebm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"business",
"nodeFrom":"ebm",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"ebm",
"name":"EBM on FHIR"},

"FHIR/FHIM Profile Builder":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-fhim-p-b",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"fhir-fhim-p-b",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-fhim-p-b",
"name":"FHIR/FHIM Profile Builder"},

"FHIR as an APIR":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-apir",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-apir",
"name":"FHIR as an APIR"},

"FHIR Care Plan":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-care-plan",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf06",
"nodeFrom":"fhir-care-plan",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"fhir-care-plan",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-care-plan",
"name":"FHIR Care Plan"},

"FHIR Clinical Reasoning":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-clin-reason",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"fhir-clin-reason",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"fhir-clin-reason",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"fhir-clin-reason",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"fhir-clin-reason",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"fhir-clin-reason",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"fhir-clin-reason",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-clin-reason",
"name":"FHIR Clinical Reasoning"},

"FHIR Open API":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-open-api",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"fhir-open-api",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"fhir-open-api",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-open-api",
"name":"FHIR Open API"},

"FHIR Profile Builder(s)":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-profile",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"fhir-profile",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"fhir-profile",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-profile",
"name":"FHIR Profile Builder(s)"},

"FHIR Terminology Resources":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-profile",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"fhir-profile",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-terem-res",
"name":"FHIR Terminology Resources"},

"FHIR Composition":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-composition",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"fhir-composition",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-composition",
"name":"FHIR Composition"},

"FHIR Doc Manifest/Reference":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-doc",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf15",
"nodeFrom":"fhir-doc",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-doc",
"name":"FHIR Doc Manifest/Reference"},

"FHIR Library":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-library",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf15",
"nodeFrom":"fhir-library",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-library",
"name":"FHIR Library"},

"FHIR Catalog":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-catalog",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf15",
"nodeFrom":"fhir-catalog",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-catalog",
"name":"FHIR Catalog"},

"FHIR Workflow":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-workflow",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"fhir-workflow",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf10",
"nodeFrom":"fhir-workflow",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"fhir-workflow",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-workflow",
"name":"FHIR Workflow"},

"FHIR Subscription/Event Def":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhir-sub",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"fhir-sub",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhir-sub",
"name":"FHIR Subscription/Event De"},

"GELLO":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"gello",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf01",
"nodeFrom":"gello",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"gello",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"gello",
"name":"GELLO"},

"KAS/KNART":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"kas",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"kas",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"kas",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"kas",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"kas",
"name":"KAS/KNART"},

"vMR-CDS":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"vmr",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"vmr",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"vmr",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"vmr",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"vmr",
"name":"vMR-CDS"},

"FHIM":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"fhim",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"fhim",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"fhim",
"name":"FHIM"},

"Knowledge Artifact Conceptual Model":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"k-a-c-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"k-a-c-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"k-a-c-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"k-a-c-m",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"k-a-c-m",
"name":"Knowledge Artifact Conceptual Model"},

"Knowledge Asset Repository":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"k-a-r",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"k-a-r",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"k-a-r",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"k-a-r",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"k-a-r",
"name":"Knowledge Asset Repository"},

"Knowledge Authoring Meta Model":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"k-a-mm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"k-a-mm",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"k-a-mm",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"k-a-mm",
"name":"Knowledge Authoring Meta Model"},

"Knowledge Authoring Tooling":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"k-a-tooling",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"k-a-tooling",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"k-a-tooling",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"k-a-tooling",
"name":"Knowledge Authoring Tooling"},

"MDMI":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"mdmi",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"mdmi",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"mdmi",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"comp",
"nodeFrom":"mdmi",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"mdmi",
"name":"MDMI"},

"National Guidelines Trust":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"n-g-trust",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"n-g-trust",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"n-g-trust",
"name":"National Guidelines Trust"},

"Published Clinical Guidelines":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"p-c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf06",
"nodeFrom":"p-c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"p-c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"p-c-g",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"p-c-g",
"name":"Published Clinical Guidelines"},

"QICore FHIR IG":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"qicore",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"qicore",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"qicore",
"name":"QICore FHIR IG"},

"QUICK Data Model":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"quick",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"quick",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"quick",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"quick",
"name":"QUICK Data Model"},

"schema.org":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"schema",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"schema",
"name":"schema.org"},

"SMART":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"smart",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"smart",
"name":"SMART"},

"HL7 US Core":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"us-core",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"us-core",
"name":"HL7 US Core"},

"USCDI":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"uscdi",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"uscdi",
"name":"USCDI"},

"USPHTF Digital Health Forum":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"usphtf",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"usphtf",
"name":"USPHTF Digital Health Forum"},

"PCDEx":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"pcdex",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"pcdex",
"name":"PCDEx"},

"DEQM":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"deqm",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"deqm",
"name":"DEQM"},

"HL7 v2 Messaging":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"hl7-v2",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"semantic",
"nodeFrom":"hl7-v2",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"hl7-v2",
"name":"HL7 v2 Messaging"},

"NIEM Health":{"adjacencies":[
{"nodeTo":"initiative",
"nodeFrom":"niem",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#FF4500",
"$type":"circle",
"description":""},
"id":"niem",
"name":"NIEM Health"},

"1 Patient Portal":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"pp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"pp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"pp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"pp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"pp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"pp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"pp",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"pp",
"name":"Patient Portal"},

"2 Self Management":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"s-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"s-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"s-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"s-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"s-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"s-m",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"s-m",
"name":"Self Management"},

"3 Community Support":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"c-s",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"c-s",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"c-s",
"name":"Community Support"},

"4 Symptom Evaluation":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"s-e",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"s-e",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"s-e",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"s-e",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"s-e",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"s-e",
"name":"Symptom Evaluation"},

"5 Patient Journal":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"p-j",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"p-j",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"p-j",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"p-j",
"name":"Patient Journal"},

"6 Screening+Assessment":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"s&a",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"s&a",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"s&a",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"s&a",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"s&a",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"s&a",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"s&a",
"name":"Screening+Assessment"},

"7 Pre-visit Questionnaire":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"p-v-q",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"p-v-q",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"p-v-q",
"name":"Pre-visit Questionnaire"},

"8 Care Guideline":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf01",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf02",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf03",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf06",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf10",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"c-g",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"c-g",
"name":"Care Guideline"},

"9 Telehealth":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"telehealth",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"telehealth",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"telehealth",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"telehealth",
"name":"Telehealth"},

"10 Doco Template":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"d-template",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"d-template",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"d-template",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"d-template",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf15",
"nodeFrom":"d-template",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"d-template",
"name":"Doco Template"},

"11 Shared Decision Making":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"s-d-m",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"s-d-m",
"name":"Shared Decision Making"},

"12 Patient Dashboard":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf06",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf10",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"p-d",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"p-d",
"name":"Patient Dashboard"},

"13 Condition Mgmt":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf06",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf10",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"c-mgmt",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"c-mgmt",
"name":"Condition Mgmt"},

"14 Integrated Care Plan":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf06",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"i-c-p",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"i-c-p",
"name":"Integrated Care Plan"},

"15 Clinical Calculator":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"c-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"c-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"c-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"c-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"c-c",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"c-c",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"c-c",
"name":"Clinical Calculator"},

"16 PDMP Tool":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"pdmp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"pdmp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"pdmp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"pdmp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"pdmp",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"pdmp",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"pdmp",
"name":"PDMP Tool"},

"17 Order Set":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"o-s",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"o-s",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"o-s",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf11",
"nodeFrom":"o-s",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"o-s",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"o-s",
"name":"Order Set"},

"18 Patient Registry":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"p-r",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"p-r",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"p-r",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"p-r",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"p-r",
"name":"Patient Registry"},

"19 Care Gap Detection":{"adjacencies":[
{"nodeTo":"intervention",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf04",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf05",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf07",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf08",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf09",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf12",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}},
{"nodeTo":"csf13",
"nodeFrom":"c-g-d",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#8B008B",
"$type":"star",
"description":""},
"id":"c-g-d",
"name":"Care Gap Detection"},

"Systems View":{"adjacencies":[
{"nodeTo":"arch",
"nodeFrom":"comp",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#636453",
"$type":"ellipse",
"description":""},
"id":"comp",
"name":"SYSTEMS VIEW"},

"Functional":{"adjacencies":[
{"nodeTo":"arch",
"nodeFrom":"business",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#636453",
"$type":"ellipse",
"description":""},
"id":"business",
"name":"FUNCTIONAL VIEW"},

"Semantic":{"adjacencies":[
{"nodeTo":"arch",
"nodeFrom":"semantic",
"data":{"$color":"#557EAA",
"$type":"line"}}],
"data":{"$color":"#636453",
"$type":"ellipse",
"description":""},
"id":"semantic",
"name":"SEMANTIC VIEW"},

};